In [3]:
import numpy as np
import matplotlib.pyplot

numpy array incelemesi numpy dizileri

In [4]:
myList = [20,30,40]
np.array(myList)

array([20, 30, 40])

In [5]:
myListMatrix = [[20,30,40],[50,60,70],[-10,-20,-30]]
np.array(myListMatrix)

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [-10, -20, -30]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#LİNSSPACE doğrusal boşluk  iki değer arasını eşit parçalara böler

In [7]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [8]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#RANDOM NUMPY İÇİN
  randn float değerlerle matrix şeklinde döndüreme yapar 
  randint int olarak tek bir array listesi şeklinde dönüş yapar

In [21]:
np.random.randn(10,5)

array([[-1.96394748, -0.52171156, -1.47409258, -0.56563597, -0.28584368],
       [-2.14466826, -1.38242492, -0.81938644,  0.29294296,  0.1648735 ],
       [ 0.33106063, -0.01344608, -0.04240439,  0.29420723, -1.17275583],
       [ 0.1110968 ,  1.44577021,  0.40630584,  0.30632086, -0.31640512],
       [-0.59514288, -0.24337368,  0.60048541, -0.77306639, -0.5018579 ],
       [-0.85872272, -0.68611004, -0.95131304, -0.48606372,  0.18243503],
       [ 0.41607983, -1.74309376, -0.74751848,  1.22463104, -1.58509968],
       [ 0.01140804, -0.61984987, -0.38835264, -0.35704792,  1.05881468],
       [ 0.18015377,  0.18302264, -0.05832326, -1.1103038 ,  0.41661674],
       [-0.52926206, -0.25882967, -1.19221666,  1.10128671, -1.33579229]])

In [11]:
myRndArray = np.random.randn(1,25,5)
myRndArray

array([[[-1.8502924 ,  0.29279165, -1.89207671,  1.07483623,
         -0.59371543],
        [ 0.24609735,  0.91355284,  0.62838888, -0.65214592,
         -1.21448135],
        [ 0.47585184,  0.83201775,  0.89820632, -1.42255103,
         -1.12390809],
        [-0.2872434 , -0.60263574,  0.02115004,  2.34705695,
          0.60583941],
        [-1.32904831, -0.60793209, -0.02085286,  0.76752421,
          0.43951598],
        [-1.04921982, -1.20380783, -0.30165172, -1.93669474,
         -1.33794935],
        [ 1.72514848,  0.19757214, -1.28894861,  0.17726326,
          1.70385226],
        [-0.46577485,  1.08889865,  0.74994914,  0.17909288,
         -0.01435017],
        [-0.56744907,  0.03418786,  0.10043451, -0.11358805,
         -1.32323869],
        [ 0.19970205,  0.3120871 ,  0.57169236,  0.4962158 ,
          0.78457076],
        [ 0.4963094 ,  0.11713446, -2.16172881, -1.37204721,
          1.63615893],
        [-0.11924028,  0.44841751,  1.13911417,  0.05153713,
          0.120

In [13]:
myNpArray = np.arange(30)
myNpArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
myNpArray.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
myNewRndArry = np.random.randint(2,140,50)
myNewRndArry


array([ 77,  18,  63,  79,  98,  64,  94,   2,  93,   5, 135,  76,  29,
       139,  25,  21,  69,  53,  62,  49,  77,  87,  70,  73, 139,  50,
        79,  58,  70,  11, 116,  21,  20, 119,  80,  84,  64,  34,  12,
       110,   3,  25,  99,  92,  51, 103,  43, 102,  58,   6])

In [26]:
myNewRndArry.max()

137

In [31]:
myNewRndArry[3 : 5]

array([79, 98])

In [44]:
myNewList1 = list(range(1,15,2))

In [47]:
myNewList1[3:8] = -5

TypeError: can only assign an iterable

In [49]:
newNpArray = np.arange(0,24)

In [52]:
slicing = newNpArray[12:19]
slicing

array([12, 13, 14, 15, 16, 17, 18])

In [53]:
slicing[:]=700

In [54]:
slicing

array([700, 700, 700, 700, 700, 700, 700])

In [55]:
newNpArray

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 700,
       700, 700, 700, 700, 700, 700,  19,  20,  21,  22,  23])

In [78]:
newNpArray2 = np.arange(25,50,2)

In [79]:
newNpArray3 =newNpArray2.copy()

In [83]:
slicing1=newNpArray3[7:12]

In [87]:
slicing1[:]=800


In [88]:
newNpArray3


array([ 25,  27,  29,  31,  33,  35,  37, 800, 800, 800, 800, 800, 700])

In [89]:
newNpArray2

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49])

# MATRİXLER İLE İŞLEME

In [90]:
myNewRndArryMatrix = np.random.randint(2,140,20)

In [91]:
myNewRndArryMatrix.reshape(4,5)

array([[ 51,  90,  34,  47,  55],
       [ 61,  91, 115,  51,   8],
       [ 92,  13,  25, 119,  67],
       [101,  88,  77,  95,  35]])

In [101]:
newListMatrix = list(range(2,50,3))

In [102]:
len(newListMatrix)

16

In [103]:
myNewListToMatrix = np.array(newListMatrix)

In [115]:
my =myNewListToMatrix.reshape(4,4)
my

array([[ 2,  5,  8, 11],
       [14, 17, 20, 23],
       [26, 29, 32, 35],
       [38, 41, 44, 47]])

In [116]:
my[0][2]

8

In [117]:
my[0,2]

8

In [124]:
my[2:,3]

array([35, 47])

In [125]:
my[[0,1]]

array([[ 2,  5,  8, 11],
       [14, 17, 20, 23]])