In [1]:
import numpy as np

In [2]:
np.full((2, 3), 5)


array([[5, 5, 5],
       [5, 5, 5]])

In [8]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:

newRndMatrix = np.random.randint(2,50,25)
newRndMatrix

array([49, 38, 36, 17, 10,  7, 37, 17,  4,  3, 38, 10, 42, 38, 21, 42,  5,
       24, 26, 47, 20, 19, 35, 48, 12])

In [13]:
newRndMatrix.reshape(5,5)

array([[49, 38, 36, 17, 10],
       [ 7, 37, 17,  4,  3],
       [38, 10, 42, 38, 21],
       [42,  5, 24, 26, 47],
       [20, 19, 35, 48, 12]])

In [18]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,-1)

In [20]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])